[workspace]
resolver = "2"

members = [
  "geomedea",
  "geomedea_geozero"
]

[workspace.dependencies]
# geozero = { git = "https://github.com/michaelkirk/geozero", branch = "mkirk/update-fgb" }
geozero = { path = "../geozero/geozero" }

