[workspace]
resolver = "2"

members = [
  "geomedea",
  "geomedea_geozero"
]

[workspace.dependencies]
# Waiting for release
geozero = { git = "https://github.com/georust/geozero", commit = "8501fedf288adc851d08a367f8f651ee643d4bed" }
# geozero = { path = "../geozero/geozero" }

